### ISSUE TITLE
character limit

### ISSUE THREAD

**Issue by Ahmedshubber** [nunosans/currency#38]
@cloudhead @jackveiga @alvesjtiago @nunosans @jonathontoon First of all this project is mazing. But I have two questions. The first is why is there a character limit of 8 numbers. What if I want to enter in a  higher conversion. When I change the number the converter sets back to zero and is unable to function. My second question is, is it possible to use a textfield instead of a button for the converter

**Comment by jackpaster** [comment]
Also do I have to pay for the API that's included in the project.

**Comment by nunosans** [comment]
@Ahmedshubber Thanks

> why is there a character limit of 8 numbers
Currencies can have up to 8 digits and 3 decimal places. That alongside the currency symbol, which sometimes can be up to 3 characters, makes the string quite long. The limit is to make sure the text remains legible in all device sizes.

> What if I want to enter in a higher conversion
That is not currently supported by the app. Again, it's not a bug, it's a design decision. The app is made primarily for travellers. Some currencies have high digit values, but even in those cases 8 digits is enough.

> When I change the number the converter sets back to zero and is unable to function
This is an issue. Can you provide:
- All steps necessary to produce this issue
- Your device model
- Your device iOS version
- Your Currency version

> My second question is, is it possible to use a textfield instead of a button for the converter
That would disable touch events on the element, like tap and swipe. There are ways around it, but using a button was the simplest implementation

**Comment by nunosans** [comment]
@jackpaster No, the API is free to use

**Comment by jackpaster** [comment]
I sent you an email

**Comment by nunosans** [comment]
@jackpaster 

> I have a shopping app and I need a textfield or button to enter a price for an item in over 100 types of currencies. Your project is great for it but there are some issues. That's why I'd like to skype u

The most relevant files for you are the `Coin.swift` and the `Converter.swift` classes. You should be able to take the logic and repurpose it for your application.
