### ISSUE TITLE
Licences for open source software

### ISSUE THREAD

**Issue by danpalmer** [nunosans/currency#7]
Hi, I noticed that Currency uses SWXMLHash, which is licenced under the MIT licence. This licence requires that it is distributed along with the software it is used in.

I suggest adding a "Licences" section to the settings bundle, and just including the licence (and any future additional licences) there in plain text.

**Comment by nunosans** [comment]
I've added an "Acknowledgments" section to the settings bundle with the licence for SWXMLHash in this commit: b5377c76ce88e2ed6eed48e958e1f83f0a4f8601. I will keep adding new licences there. Thanks for the feedback 😃
