### ISSUE TITLE
French (fr) translation 

### ISSUE THREAD

**Issue by slim-e** [nunosans/currency#8]
## TODO
How can I help ? :fr:

**Comment by nunosans** [comment]
Thanks @slim-e 😁 

At the moment I am sending people a zip file with all the text and some images and asking people so send me the translations back. I don't have a different process in place. Shall we go with it?

Here's how it works:
1. You download and open the [translation kit](http://currency.nunocoelhosantos.com/archives/Currency_for_iOS_Translation_Kit.zip). You will see images and two text documents.
2. Pick the text document you prefer (Word document or RTF) and edit it with the translations.
3. Have a look at the images included in the archive for reference.
4. Share the text document back.

**Comment by slim-e** [comment]
@nunosans Understood 👍

**Comment by slim-e** [comment]
@nunosans Here you go brother 💪 
[Text (French).zip](https://github.com/nunosans/currency/files/644268/Text.French.zip)

**Comment by nunosans** [comment]
Thank you for this @slim-e. I'll close the issue once it's implemente 👍

**Comment by slim-e** [comment]
@nunosans Awesome

**Comment by nunosans** [comment]
Merged here 3103914251c47d502e4e712734ca6a159df99014

**Comment by nunosans** [comment]
Hey @slim-e, Can I ask you for a final check on my translation?

I've made a translation of the currency names from searching online. But these translations can be wrong.

I have a spreadsheet with the names here: https://docs.google.com/spreadsheets/d/1IXiqBi4qUAakxJVrOeQWNeCcAnkB2OK4ga5-o_OADD0/edit?usp=sharing

Can you check the column "French Final" and see if the names are written correctly? Please rewrite them or comment.

Thanks,
Nuno

**Comment by slim-e** [comment]
@nunosans Understood, will do.

**Comment by slim-e** [comment]
@nunosans 
There are some little mistakes and inconsistency in the French structure, I'd like to ask you about 😕 

Sometimes you write : `[CURRENCY] from [COUNTRY_NAME]`
and sometimes : `[COUNTRY_NAME]'s [CURRENCY]`
Which one would you like to use ?

If you don't mind having both, I can just proofread what you got and fix the mistakes 💪

**Comment by nunosans** [comment]
Thanks for the diligence.

The preferred format is: `[ADJECTIVE_COUNTRY_REGION] [CURRENCY]`.
Examples: `Japanese Yen`, `Swiss Franc`, `Thai Baht`.

Many currencies are not from a specific country or region, in those cases having only [Currency] is correct.
Examples: `Euro`, `Bitcoin`.

But having other formats is not a problem. The goal is to make searching a currency easier by not only having the currency name but also the country it belongs too. That way, a user who searches `korea` can easily find `South Korean Won`.

**Comment by slim-e** [comment]
@nunosans 
Alright, understood.
I'll make the needed changes according to theses specs then ☝️

**Comment by slim-e** [comment]
@nunosans DONE 💪

**Comment by nunosans** [comment]
@slim-e thanks mate 💯
